### ISSUE TITLE
Exceptions in roll_die

### ISSUE THREAD

**Issue by TetroVolt** [xylafur/dnd-generator#5]
so the main file dnd-gen is importing the wrong file. It should be lib.random_die. I fixed that in my version of the file. Also there is no lib.InvalidArgumentException in the repo, but the random_die module still imports it.

**Comment by TetroVolt** [comment]
Whoever wrote this are you sure you didn't mean to use TypeError, or ValueError, or IndexError? I git blamed it and THE RED HEADED ONE IS RESPONSIBLE!!!

**Comment by Acejhm** [comment]
Yep, that one's my bad.  I probably have it in my local copy.  I'll fix it when I get home.

**Comment by TetroVolt** [comment]
I did a pull request
